DROP DOMAIN IF EXISTS GENDER; CREATE DOMAIN GENDER as TEXT ;
DROP DOMAIN IF EXISTS SPECIMEN_CLASS; CREATE DOMAIN SPECIMEN_CLASS as TEXT;
DROP DOMAIN IF EXISTS SPECIMEN_TYPE; CREATE DOMAIN SPECIMEN_TYPE as TEXT;
DROP DOMAIN IF EXISTS SAMPLE_TYPE; CREATE DOMAIN SAMPLE_TYPE as TEXT;
DROP DOMAIN IF EXISTS FILE_TYPE; CREATE DOMAIN FILE_TYPE as TEXT;
DROP DOMAIN IF EXISTS ANALYSIS_STATE; CREATE DOMAIN ANALYSIS_STATE as TEXT;
DROP DOMAIN IF EXISTS LIBRARY_STRATEGY; CREATE DOMAIN LIBRARY_STRATEGY as TEXT;
