echo "Starting ID Server..."
echo '$POSTGRES_HOST='$POSTGRES_HOST
echo '$POSTGRES_PORT='$POSTGRES_PORT
echo '$POSTGRES_DB='$POSTGRES_DB
echo '$POSTGRES_USER='$POSTGRES_USER
echo '$POSTGRES_PASSWORD='$POSTGRES_PASSWORD

/dcc-id-server/bin/dcc-id-server start \
	set.SPRING_DATASOURCE_URL="jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}" \
	set.SPRING_DATASOURCE_USERNAME=$POSTGRES_USER \
	set.SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD \
	wrapper.java.addition.1="-Dsecurity.basic.enabled=false" \
	set.SECURITY_BASIC_ENABLED="false"
