echo "Starting ID Server..."
echo '$ID_HOME='$ID_HOME
echo '$POSTGRES_HOST='$POSTGRES_HOST
echo '$POSTGRES_PORT='$POSTGRES_PORT
echo '$POSTGRES_DB='$POSTGRES_DB
echo '$POSTGRES_USER='$POSTGRES_USER
echo '$POSTGRES_PASSWORD='$POSTGRES_PASSWORD
echo '$AUTH_SERVER_URL='$AUTH_SERVER_URL
echo '$AUTH_SERVER_CLIENTID='$AUTH_SERVER_CLIENTID
echo '$AUTH_SERVER_CLIENTSECRET='$AUTH_SERVER_CLIENTSECRET

$ID_HOME/bin/dcc-id-server start \
	set.SPRING_DATASOURCE_URL="jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}" \
	set.SPRING_DATASOURCE_USERNAME=$POSTGRES_USER \
	set.SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD \
	set.AUTH_SERVER_URL=$AUTH_SERVER_URL \
	set.AUTH_SERVER_CLIENTID=$AUTH_SERVER_CLIENTID \
	set.AUTH_SERVER_CLIENTSECRET=$AUTH_SERVER_CLIENTSECRET
